# name: GitHub Actions Demo
# on: 
#   push:
#     branches: [dev]
# jobs:
#   task1:
#     runs-on: ubuntu-latest
#     steps:
#       - run: 
name: Go
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEPLOY_VER: Gulag #nigger?
      YEAR: 2077
    steps:
    - uses: actions/checkout@v3
    - name: Show all folders
      run: ls -R
    - name: Print content of log.txt
      run: cat log.txt
    - name: Print Github variables
      run: echo "Hello from ${DEPLOY_VER}"