# name: GitHub Actions Demo
# on: 
#   push:
#     branches: [dev]
# jobs:
#   task1:
#     runs-on: ubuntu-latest
#     steps:
#       - run: 
name: Go
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show all folders
      run: ls -R